### ISSUE TITLE
Crash when open wireless terminal. Texture bug.

### ISSUE THREAD

**Issue by thething0** [p455w0rd/AE2WirelessTerminalLibrary#7]
AE2WTLib-1.12.2-1.0.32

When i try to open any kind of wireless terminal the game crashes
https://pastebin.com/XWcVNEh7
Also terminals itself doesn't have a texture.
https://i.imgur.com/wkqW9QE.png

**Comment by Erin-Rose** [comment]
Having the same issue... 
going to try rolling back to an old mod version

**Comment by Erin-Rose** [comment]
after a bit of messing around I found that installing: 
AE2 Wireless Terminal Library - 1.0.30
p455w0rd's Library - 2.2.134
Wireless Crafting Terminal - 3.12.93
fixes the issue for me

**Comment by p455w0rd** [comment]
using optifine?

**Comment by Erin-Rose** [comment]
not using optifine myself

**Comment by Nomad7** [comment]
After updating Enigmatica 2 Light (https://www.curseforge.com/minecraft/modpacks/enigmatica2light) to version 1.4.0 I am getting the error described above (missing texture and 'Registering texture' crash when rightclicking with a fully charged wireless crafting terminal). Not using optifine.

Edit: Seems like this already be fixed in https://github.com/p455w0rd/DankNull/issues/225 but I'm a bit new to all this modpack management stuff, do I need to report the issue to the Enigmatica team and wait for them to fix it?
Are there any other solutions short of manually updating 4 mods on the server (and the clients for our handful of players)?

Apologies for my ignorance, Minecraft has changed a lot in the last 6 years :)

**Comment by p455w0rd** [comment]
nah...niller is really good about keeping up to date..i'll shoot him a DM about the update I just pushed

**Comment by p455w0rd** [comment]
also this is fixed in 1.0.34
